// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: gateway/service.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrentItem_Type int32

const (
	CurrentItem_NORMAL CurrentItem_Type = 0
	CurrentItem_CHAKRA CurrentItem_Type = 1
)

// Enum value maps for CurrentItem_Type.
var (
	CurrentItem_Type_name = map[int32]string{
		0: "NORMAL",
		1: "CHAKRA",
	}
	CurrentItem_Type_value = map[string]int32{
		"NORMAL": 0,
		"CHAKRA": 1,
	}
)

func (x CurrentItem_Type) Enum() *CurrentItem_Type {
	p := new(CurrentItem_Type)
	*p = x
	return p
}

func (x CurrentItem_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CurrentItem_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_service_proto_enumTypes[0].Descriptor()
}

func (CurrentItem_Type) Type() protoreflect.EnumType {
	return &file_gateway_service_proto_enumTypes[0]
}

func (x CurrentItem_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CurrentItem_Type.Descriptor instead.
func (CurrentItem_Type) EnumDescriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{0, 0}
}

type CurrentItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type   CurrentItem_Type `protobuf:"varint,2,opt,name=type,proto3,enum=service.CurrentItem_Type" json:"type,omitempty"`
	Author int64            `protobuf:"varint,3,opt,name=author,proto3" json:"author,omitempty"`
	Url    string           `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Title  string           `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Icon   string           `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
}

func (x *CurrentItem) Reset() {
	*x = CurrentItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentItem) ProtoMessage() {}

func (x *CurrentItem) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentItem.ProtoReflect.Descriptor instead.
func (*CurrentItem) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{0}
}

func (x *CurrentItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CurrentItem) GetType() CurrentItem_Type {
	if x != nil {
		return x.Type
	}
	return CurrentItem_NORMAL
}

func (x *CurrentItem) GetAuthor() int64 {
	if x != nil {
		return x.Author
	}
	return 0
}

func (x *CurrentItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CurrentItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CurrentItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type SetCurrentItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string       `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Item   *CurrentItem `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *SetCurrentItemRequest) Reset() {
	*x = SetCurrentItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCurrentItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCurrentItemRequest) ProtoMessage() {}

func (x *SetCurrentItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCurrentItemRequest.ProtoReflect.Descriptor instead.
func (*SetCurrentItemRequest) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{1}
}

func (x *SetCurrentItemRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SetCurrentItemRequest) GetItem() *CurrentItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type SetCurrentItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetCurrentItemResponse) Reset() {
	*x = SetCurrentItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCurrentItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCurrentItemResponse) ProtoMessage() {}

func (x *SetCurrentItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCurrentItemResponse.ProtoReflect.Descriptor instead.
func (*SetCurrentItemResponse) Descriptor() ([]byte, []int) {
	return file_gateway_service_proto_rawDescGZIP(), []int{2}
}

var File_gateway_service_proto protoreflect.FileDescriptor

var file_gateway_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0xc0, 0x01, 0x0a, 0x0b, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69,
	0x63, 0x6f, 0x6e, 0x22, 0x1e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e,
	0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x48, 0x41, 0x4b, 0x52,
	0x41, 0x10, 0x01, 0x22, 0x59, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x18,
	0x0a, 0x16, 0x53, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x65, 0x0a, 0x0e, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x53, 0x65,
	0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61,
	0x6b, 0x75, 0x72, 0x61, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_gateway_service_proto_rawDescOnce sync.Once
	file_gateway_service_proto_rawDescData = file_gateway_service_proto_rawDesc
)

func file_gateway_service_proto_rawDescGZIP() []byte {
	file_gateway_service_proto_rawDescOnce.Do(func() {
		file_gateway_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_service_proto_rawDescData)
	})
	return file_gateway_service_proto_rawDescData
}

var file_gateway_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gateway_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateway_service_proto_goTypes = []interface{}{
	(CurrentItem_Type)(0),          // 0: service.CurrentItem.Type
	(*CurrentItem)(nil),            // 1: service.CurrentItem
	(*SetCurrentItemRequest)(nil),  // 2: service.SetCurrentItemRequest
	(*SetCurrentItemResponse)(nil), // 3: service.SetCurrentItemResponse
}
var file_gateway_service_proto_depIdxs = []int32{
	0, // 0: service.CurrentItem.type:type_name -> service.CurrentItem.Type
	1, // 1: service.SetCurrentItemRequest.item:type_name -> service.CurrentItem
	2, // 2: service.GatewayService.SetCurrentItem:input_type -> service.SetCurrentItemRequest
	3, // 3: service.GatewayService.SetCurrentItem:output_type -> service.SetCurrentItemResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gateway_service_proto_init() }
func file_gateway_service_proto_init() {
	if File_gateway_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrentItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCurrentItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCurrentItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_service_proto_goTypes,
		DependencyIndexes: file_gateway_service_proto_depIdxs,
		EnumInfos:         file_gateway_service_proto_enumTypes,
		MessageInfos:      file_gateway_service_proto_msgTypes,
	}.Build()
	File_gateway_service_proto = out.File
	file_gateway_service_proto_rawDesc = nil
	file_gateway_service_proto_goTypes = nil
	file_gateway_service_proto_depIdxs = nil
}
