// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package chakrapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChakraServiceClient is the client API for ChakraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChakraServiceClient interface {
	CreateStream(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*StreamInfo, error)
}

type chakraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChakraServiceClient(cc grpc.ClientConnInterface) ChakraServiceClient {
	return &chakraServiceClient{cc}
}

func (c *chakraServiceClient) CreateStream(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*StreamInfo, error) {
	out := new(StreamInfo)
	err := c.cc.Invoke(ctx, "/service.ChakraService/CreateStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChakraServiceServer is the server API for ChakraService service.
// All implementations must embed UnimplementedChakraServiceServer
// for forward compatibility
type ChakraServiceServer interface {
	CreateStream(context.Context, *CreateRequest) (*StreamInfo, error)
	mustEmbedUnimplementedChakraServiceServer()
}

// UnimplementedChakraServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChakraServiceServer struct {
}

func (UnimplementedChakraServiceServer) CreateStream(context.Context, *CreateRequest) (*StreamInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStream not implemented")
}
func (UnimplementedChakraServiceServer) mustEmbedUnimplementedChakraServiceServer() {}

// UnsafeChakraServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChakraServiceServer will
// result in compilation errors.
type UnsafeChakraServiceServer interface {
	mustEmbedUnimplementedChakraServiceServer()
}

func RegisterChakraServiceServer(s grpc.ServiceRegistrar, srv ChakraServiceServer) {
	s.RegisterService(&ChakraService_ServiceDesc, srv)
}

func _ChakraService_CreateStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChakraServiceServer).CreateStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ChakraService/CreateStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChakraServiceServer).CreateStream(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChakraService_ServiceDesc is the grpc.ServiceDesc for ChakraService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChakraService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.ChakraService",
	HandlerType: (*ChakraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStream",
			Handler:    _ChakraService_CreateStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chakra/service.proto",
}
